import { DocumentFormData } from '../types';
import { RandomHelper } from '../utils/random.helper';
import { FileHelper } from '../utils/file.helper';

// ─── Static test data (fixed, deterministic) ───────────────────────────────────

export const DocumentData = {
  valid: {
    documentName: 'Calibration Certificate Rev1',
    documentType: 'CERTIFICATE',
    supplier:     'IFM Electronic',
    supplierDocId:'DOC-CAL-001',
    remarks:      'Automated test document',
  } as DocumentFormData,

  specialChars: {
    documentName: '!@#$%^&*()_+-=[]{}|;:,./<>?',
    documentType: undefined,
    supplier:     undefined,
  } as DocumentFormData,

  longName: {
    documentName: RandomHelper.longString(255),
    documentType: undefined,
    supplier:     undefined,
  } as DocumentFormData,
};

// ─── Dynamic data (unique per run — safe for parallel execution) ───────────────

export function generateDocumentData(): DocumentFormData {
  return {
    documentName:  RandomHelper.documentName('Auto Doc'),
    documentType:  undefined,
    supplier:      undefined,
    supplierDocId: RandomHelper.supplierDocId(),
    remarks:       'Generated by automation',
  };
}

// ─── JSON-driven data (loads from test-data/document.json) ────────────────────

export interface DocumentTestCase {
  id:           string;
  description:  string;
  input:        DocumentFormData;
  expectError:  boolean;
  errorField?:  string;
}

export function loadDocumentTestCases(): DocumentTestCase[] {
  try {
    return FileHelper.readTestData<DocumentTestCase[]>('document.json');
  } catch {
    return [];
  }
}
